module.exports = {
	'apiKey.id': 'string',
	'apiKey.key': 'string',
	'apiKey.encoding': 'string',
	'callbackUrl': 'string',
	'shorten': 'boolean',
	'uriSchemaPrefix': 'string',
	'locale': 'string',
	'fiatCurrency': 'string',
	'fiatPrecision': 'integer',
	'buyLimit': 'number',
	'coinValues': 'array-number',
	'coinValueIncrement': 'number',
	'billValues': 'array-number',
	'webUrl': 'string',
	'platformSockUri': 'string',
	'pingSockUri': 'string',
	'strictTls': 'boolean',
};
